### ISSUE TITLE
Kubevirt-storage-checkup was failing when a virtual machine is already created.

### ISSUE THREAD

**Issue by sakshi-garg1** [kiagnose/kubevirt-storage-checkup#41]
Environment: 
OCP cluster version: 4.18.0-rc.1
![image](https://github.com/user-attachments/assets/911d359f-630d-49d5-bf8a-f86d3e958bf5)

Openshift Virtualization version:  4.17.2
![image](https://github.com/user-attachments/assets/18152eeb-19f9-40dd-b674-6e4e3843f18a)

Only 1 driver storage class is present as default. 

Case 1: Running this storage checkup without manually creating any Virtual Machines , the check is passing successfully. While running this test also verified manually that the PVCs being created were all in bound state and using my driver storage class.
![image](https://github.com/user-attachments/assets/02c326f1-9a7a-4d0e-b0e3-47b8caba5346)

Case 2: Creating 1 Virtual Machine manually as shown below and running storage checkup test, the checkup fails with error: hotplug volume ready:timed out waiting for the condition. 
![image](https://github.com/user-attachments/assets/0d281e42-43c0-4325-8b45-10df7cce6616)
![image](https://github.com/user-attachments/assets/02588c53-60bd-4e08-af7b-da8b37a27875)

Seems not a driver issue as case 1 certifies that. 
Why it is failing for case 2. Is it an expected behavior?
Is it related to rc builds that this test throws up this issue because when using Openshift virtualization version 4.17.2 with openshift cluster 4.17 case 2 passes as well.

**Comment by sakshi-garg1** [comment]
Any update on this?

**Comment by arnongilboa** [comment]
> Any update on this?

Note you are using 4.18.0-rc.1 that has a known hotplug [bug](https://issues.redhat.com/browse/OCPBUGS-46531)
For running the checkup it's better to use a stable release (and not candidates).
If that doesn't solve the issue, try to extend `param.vmiTimeout` to 10m.

**Comment by satyakonduri** [comment]
Hi @arnongilboa,

I tried setting the parm.vmiTimeout parameter to a 10-minute timeout but am still encountering the same issue.
Could you please let us know if there are any other configurations we should try to resolve this?
Config used: 

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-checkup-config
  namespace: default
data:
  spec.timeout: 10m
  spec.param.vmiTimeout: 10m
---
apiVersion: batch/v1
kind: Job
metadata:
  name: storage-checkup
  namespace: default
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccount: storage-checkup-sa
      restartPolicy: Never
      containers:
        - name: storage-checkup
          image: quay.io/kiagnose/kubevirt-storage-checkup:main
          imagePullPolicy: Always
          env:
            - name: CONFIGMAP_NAMESPACE
              value: default
            - name: CONFIGMAP_NAME
              value: storage-checkup-config
```

![image](https://github.com/user-attachments/assets/35d2133c-799a-4ecb-b060-43e04f09df73)

Thank You.!
